// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR9l8O0qrmY52d9QgeFfzD_7CQnJc7a4I',
    appId: '1:868931920364:web:7c690b2f7890371a0c20c9',
    messagingSenderId: '868931920364',
    projectId: 'fb-db-d269b',
    authDomain: 'fb-db-d269b.firebaseapp.com',
    storageBucket: 'fb-db-d269b.appspot.com',
    measurementId: 'G-MBH82EKHNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZjlDABwxslUJbeszX4g-Q6SL9dpLbXt8',
    appId: '1:868931920364:android:d9cc4091e3a0ade80c20c9',
    messagingSenderId: '868931920364',
    projectId: 'fb-db-d269b',
    storageBucket: 'fb-db-d269b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3_2epWOKXdjbqAp-v9WdLLDziwHLREE',
    appId: '1:868931920364:ios:8bf919b1d99b0c9a0c20c9',
    messagingSenderId: '868931920364',
    projectId: 'fb-db-d269b',
    storageBucket: 'fb-db-d269b.appspot.com',
    iosBundleId: 'com.example.databaseCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd3_2epWOKXdjbqAp-v9WdLLDziwHLREE',
    appId: '1:868931920364:ios:8bf919b1d99b0c9a0c20c9',
    messagingSenderId: '868931920364',
    projectId: 'fb-db-d269b',
    storageBucket: 'fb-db-d269b.appspot.com',
    iosBundleId: 'com.example.databaseCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR9l8O0qrmY52d9QgeFfzD_7CQnJc7a4I',
    appId: '1:868931920364:web:4e42dbc77b9235b40c20c9',
    messagingSenderId: '868931920364',
    projectId: 'fb-db-d269b',
    authDomain: 'fb-db-d269b.firebaseapp.com',
    storageBucket: 'fb-db-d269b.appspot.com',
    measurementId: 'G-1EPBKSBJ5F',
  );
}
